### PR TITLE
Implement async send

### PR DESCRIPTION
**Pull request by nickolay-github**
Hi!
Thanks for the helpful library!

In the PR I added an implementation of the asynchronous `send` function

As I understood, having seen these tickets (#71 #84 ), this feature would be useful) 

I will be glad to receive comments and remarks!

### CODE REVIEW

**Comment by rveachkc** [comment]
I'm going to need some time to review this, as I'm not familiar with httpx.  Truthfully, I'd prefer an async send method that kept with the standard library+requests, but I'll do some research on that.

Additional thoughts:

* As is, this is also going to require some changes to the `setup.py` to account for the additional dependencies.
* This will also make this also require python3. I have tried to avoid this in the past, but I think it's time to move forward with that.    In doing so, I would want to update away from the legacy connector cards, and move to the newer Action cards.

**Comment by nickolay-github** [comment]
Unfortunately, the standard python+requests library is not enough.
The Requests library does not support asynchronous calls.
I chose httpx, mainly because the library is very similar to requests, only with asynchronous: method signatures and API are compatible with requests and there is an indication in the documentation of the original requests that httpx is a good asynchronous alternative(https://docs.python-requests.org/en/latest/user/advanced/#asynchronous-requests).

- yes, forgot about setup.py, I'll add it, thanks
- could you describe the idea of replacing connector cards with action cards in more detail?

**Comment by rveachkc** [comment]
If this is going to be added to the setup.py, I'd really prefer httpx be installed if somebody installs with a `pip install pymsteams[async]`.  That way, if somebody still needs to install on py2, it won't break.

This library uses the [actionable message card](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-connectors#creating-messages-through-office-365-connectors-in-microsoft-teams) api, which uses the [Legacy actionable message](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference) format.

The first note for this reference is:

> This document describes the original JSON format for the actionable message card format. For actionable messages sent via email, this has been replaced with the Adaptive Card format. Microsoft recommends that new actionable message integrations use the Adaptive Card format, and existing integrations consider updating to Adaptive Card format. The Adaptive Card format is required to support Outlook on iOS and Android. However, if you are sending actionable messages via an Office connector, or to a Microsoft Teams connector, you must continue to use the message card format.

I'd like to eventually work in code to use this new format instead: https://docs.microsoft.com/en-us/outlook/actionable-messages/adaptive-card

**Comment by maslyankov** [comment]
Any update on merging this?

**Comment by rveachkc** [comment]
Apologies for the delay. Between the holidays and fitness goals, I've had limited personal time until recently.

I'm wanting to make a couple changes before merging  to master, so I created a new branch, and I'm working on those in #116.  Since async sending is a fairly significant change, this will be released as version `0.2.0`.

I would like to comment on two things about this PR that really delayed my review. Had that not been the case, it probably would have been merged to master and released much sooner.

### No documentation was included in the pull request

This needs to be done before this is released, and it would have been much easier to review had that been done.  Honestly, I don't mind learning about `httpx` and `asyncio`, but I have zero need for it, so I had to dedicate some time to sit down and learn it.

### Style and formatting updates included in the initial commit.

Honestly, when I first read through this PR, I got frustrated needing to review many non-functional changes alongside the actual enhancement.

I understand....my formatting was not ideal, but in the future, please separate style and formatting changes from the functional one.

Ideally, I'd like them in separate PR's, but at minimum, push them in separate commits.

**Pull request merged**
