### PR TITLE
Created Adaptive card function and also mention user is available on this card

### PR DESCRIPTION
**Pull request by YugoHino**
Hi

I love this repository and our time is so saved. Thank you so much!!
We wanted to mention use on Teams, but connector card doesn't allow us to mention users yet.

This is new feature which is available for the type of Adaptive card. Now Adaptive card allows us to mention users. 

https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=adaptive-md%2Cconnector-html#user-mention-in-incoming-webhook-with-adaptive-cards

I am new to OSS activity. Let me know if something wrong with pull request rules.

Thanks,
Hino

### CODE REVIEW

**Comment by ALERTua** [comment]
I would be thankful for Python2-compatible code on this one:
on Python 2 super() call on line 7 has to be with arguments
on Python 2 F-sting on line 145 is not supported.
these changes won't ruin Python 3 support.
thank you very much

**Comment by YugoHino** [comment]
Thank you for your comment. I will fix it.

**Comment by YugoHino** [comment]
Fixed and checked those points. Could you check this again.

Thanks,
Hino

**Comment by ALERTua** [comment]
I confirm your fix. Thank you!

**Comment by rveachkc** [comment]
Thanks for the PR. I will review this as time allows. Maybe this weekend?

While I can sympathize with the need to support Python 2, maintaining compatibility will create additional work. It reached end of life over 2 years ago on January 1, 2020. I don't want python2 compatibility to limit code style improvements or increase the amount of work required to improve this library.  In fact, per #119, the master branch already requires python3.

I would be willing to maintain and review pull requests on a python2 branch, but I don't feel that python 2 compatibility should limit code improvements.

**Comment by YugoHino** [comment]
I agree with that. For testing python 2 compatibility on my environment, I needed to install python 2 additionally. Also as noted, #119 async section is necesarry to be commented out while testing because this is not supported for python 2 until it's fixed.

**Comment by maximBelitski** [comment]
Hi guys! Any progress on merging the PR ? Very desired functionality :)

**Comment by dmonlineuk** [comment]
+1 on this being merged soon please

**Comment by rveachkc** [comment]
This is going to take a bit of time for me to review the adaptive card api and prepare for release.
I just haven't found the time to do it yet.

**Comment by nirajdesai29** [comment]
If you can change the size of adaptive card to Large isntead of medium, that would be handy, as some messages maybe big. When trying the setup, it works great, but due to medium size, only half sized card is dispalyed and extra text are not displayed.

**Comment by blacksheep0815** [comment]
I would also appreciate to get those changes released. :-)

Question: Can multiple people be mentioned with the changes here or just 1?

**Comment by YugoHino** [comment]
Multiple people mention is available on this PR.

**Comment by anuragladdha-ml** [comment]
when are we planning to merge this and release?

**Comment by nirajdesai29** [comment]
@rveachkc if you can get it released fast , would be very helpful

**Comment by rveachkc** [comment]
I've been thinking about this quite a bit, but I don't think this is a direction in which I want to go.
The adaptive card api is quite expansive (https://adaptivecards.io/), but this is a very narrow implementation of it.

If adaptive cards are to be supported, are to be supported with this library, it will be in one of the two following ways:
- raw python object support, where we basically turn a dictionary into json and pass to the webhook
  - but what's the point in doing this?  why would somebody choose to use pymsteams over requests?
  - this could be a good standalone feature anyway.....
- use an additional library to provide full adaptive card support - this seems to be the best way to do it, but adding additional libraries is always a risk.  I found [pyadaptivecards](https://github.com/CiscoSE/pyadaptivecards), which at least appears to have a stable backing behind it, and two others that have been created by other developers.

So....I'm going to decline this request for now, but know that I'm thinking about it.
Expect some movement here, but in a different direction.

**Comment by YugoHino** [comment]
Thank you for thinking about it! I just wanted to mention a user on the card even it's adaptive card because there is only the way to mention user on teams incomming webhook now. But I understand your point as commented. I will find other way to mention a user on teams incomming webhook such like using the library you commented. 
Thank you so much!

**Pull request closed without merging**
